test: add tests on handling of duplicate matrix selectors
rapidsai/dependency-file-generator pull request #102
Opened 2024-07-23 14:14 UTC by jameslamb

Contributes to https://github.com/rapidsai/build-planning/issues/31.

Over in https://github.com/rapidsai/devcontainers/pull/365, I'm proposing a change that depends on how `rapids-dependency-file-generator` handles duplicates in `--matrix` selectors.

See https://github.com/rapidsai/devcontainers/pull/365#discussion_r1687121294.

This proposes adding tests covering that behavior, to reduce the risk of accidentally removing that support in future refactorings.

2024-07-23 14:21 UTC, KyleFromNVIDIA requested changes
This is fine, but if it was me, I would have modified https://github.com/rapidsai/devcontainers/pull/365#discussion_r1687121294 to detect if the user is overriding `cuda_suffixed` to avoid passing more than one value.

Let's explicitly document this behavior too.

2024-07-23 14:47 UTC, jameslamb commented
> *This is fine, but if it was me, I would have modified https://github.com/rapidsai/devcontainers/pull/365#discussion_r1687121294 to detect if the user is overriding cuda_suffixed to avoid passing more than one value.*

The simplest implementation I can think of involves tracking the defaults as a bash associative array, splitting each `--matrix-entry` value by `=` into `(key, value)`, and then indexing into that associative array with them.

That was more complexity than I was comfortable with for this purpose, but I'm willing to try it. Let's please not hold up https://github.com/rapidsai/devcontainers/pull/365 or this PR for that though. I'd like to try to get https://github.com/rapidsai/devcontainers/pull/365 and the corresponding `dependencies.yaml` changes out before code freeze for 24.08 (end of day tomorrow). 

> *Let's explicitly document this behavior too.*

Document what, where? I don't understand what you're asking for, sorry.

2024-07-23 14:49 UTC, KyleFromNVIDIA commented
> Document what, where? I don't understand what you're asking for, sorry.

Document the fact that the last duplicate is the one that DFG actually uses, which is what this PR is all about.

2024-07-23 14:55 UTC, KyleFromNVIDIA approved these changes

2024-07-23 14:56 UTC, KyleFromNVIDIA commented
The README, because that's what the end user is going to see.

2024-07-23 14:57 UTC, jameslamb commented
Gotchu! Ok yeah no problem, I agree that's a good addition.

Thanks for the quick review, always appreciated!

2024-07-23 14:58 UTC, merged

2024-09-23 17:30 UTC, GPUtester commented
:tada: This PR is included in version 1.15.0 :tada:

The release is available on:
- [GitHub release](https://github.com/rapidsai/dependency-file-generator/releases/tag/v1.15.0)
- [PyPI release](https://pypi.org/project/rapids-dependency-file-generator/)
- [Conda release - rapidsai](https://anaconda.org/rapidsai/rapids-dependency-file-generator)
- [Conda release - rapidsai-nightly](https://anaconda.org/rapidsai-nightly/rapids-dependency-file-generator)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: